from typing import Protocol
from uuid import UUID


class ImportSpool(Protocol):
    def write(self, batch_id: UUID, content: bytes) -> None: ...
    def read(self, batch_id: UUID) -> bytes: ...
    def remove(self, batch_id: UUID) -> None: ...
