from typing import Protocol
from uuid import UUID

from backend.domain.entities.background_job import BackgroundJob


class BackgroundJobRepository(Protocol):
    def get_for_key(self, kind: str, user_id: UUID, key: str) -> BackgroundJob | None: ...
    def get_for_resource(self, kind: str, resource_id: UUID) -> BackgroundJob | None: ...
    def add(self, job: BackgroundJob) -> None: ...
    def complete(self, job_id: UUID, claim_token: UUID, *, progress: dict) -> None: ...
    def assert_owned(self, job_id: UUID, claim_token: UUID) -> None: ...
    def fail(self, job_id: UUID, claim_token: UUID) -> None: ...
